export enum Skills {
    Angular = 'Angular',
    React = 'React',
    Vue = 'Vue',
    Javascript = 'JavaScript',
    Typescript = 'TypeScript',
    JSON = 'JSON',
    Java = 'Java',
    Python = 'Python',
    CSharp = 'C#',
    NodeJS = 'Node.js',
    SQL = 'SQL',
    NoSQL = 'NoSQL',
    AWS = 'AWS',
    Azure = 'Azure',
    Docker = 'Docker',
    DotNet = '.NET',
    Spring = 'Spring',
    Hibernate = 'Hibernate',
    REST = 'REST',
    GraphQL = 'GraphQL'
}